version: '3'
services:
  nginx:
    ports:
      - "3000:80"
      
  backend:
    build: 
      context: ./backend
      dockerfile: Dockerfile
      target: development
    volumes:
      - ./backend:/app:ro
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=test
      - MONGO_PASSWORD=test
      - SESSION_SECRET=secret
    depends_on:
      - mongo
    command: npm run dev

  frontend:
    build: 
      context: ./frontend
      dockerfile: Dockerfile
      target: development
    ports:
      - "8080:8080" 
    environment:
      - PORT=8080
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm run dev

  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=test
      - MONGO_INITDB_ROOT_PASSWORD=test
    volumes:
      - mongo-db:/data/db
    
  redis:
    image: redis

volumes:
  mongo-db: